### ISSUE TITLE
Retro PC Background not showing up

### ISSUE THREAD

**Issue by joaovsa** [dtinth/atom-aesthetic-ui#12]
### Description
Inside project folder navigation tab (tree-view), the white + retro PC background is not showing up.

### Steps to Reproduce

1. Initialize Atom 1.17.0
2. Open Project Tab

**Expected behavior:** See folders folders inside the tab with a background

**Actual behavior:** Actually sees the folders but background doesn't show up

**Reproduces how often:** Every time Atom is started up.

### Versions
Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

OS: W10 Home x64

### Additional Information

How it is:

![image](https://cloud.githubusercontent.com/assets/11942940/26227125/cb4a1c7a-3c06-11e7-8320-82b29e6be0fb.png)

**Comment by dtinth** [comment]
@joaovsa 

Ｔｈｉｓ　ｉｓｓｕｅ　ｉｓ　ｆｉｘｅｄ　ｂｙ　＃１１．
Ａ　ｎｅｗ　ｖｅｒｓｉｏｎ，　４．０．０，　ｈａｓ　ｂｅｅｎ　ｒｅｌｅａｓｅｄ．
Ｃｏｕｌｄ　ｙｏｕ　ｐｌａｅｓｅ　ｖｅｒｉｆｙ　ｉｆ　ｉｔ　ｉｓ　ｗｏｒｋｉｎｇ　ｎｏｗ？

Ｉｆ　ｉｔ　ｗｏｒｋｓ，　ｐｌｅａｓｅ　ｋｉｎｄｌｙ　ｃｌｏｓｅ　ｔｈｉｓ　ぃｓｓｕｅ．
Ｔｈａｎｋｓ！

**Comment by joaovsa** [comment]
Ｔｈａｎｋｓ 友達 !
