### ISSUE TITLE
TreeView is black/white

### ISSUE THREAD

**Issue by abejfehr** [dtinth/atom-aesthetic-ui#3]
I love this theme, but the TreeView is plain black/white. I think it would be cool if it looked like the Windows 98 TreeView in this screenshot:

![](http://winsupersite.com/content/content/127892/showcase/ty_using_04_05_01.gif)

I was thinking of playing around with the styles this evening, would you be interested in accepting a pull-request if I managed to pull it off?

**Comment by dtinth** [comment]
Ｃｈａｌｌｅｎｇｅ　ａｃｃｅｐｔｅｄ．

**Comment by dtinth** [comment]
Ｐｌｅａｓｅ　ｎｏｔｅ，
ｔｈｉｓ　ｔｈｅｍｅ　ｉｓ　ｂａｓｅｄ　ｏｎ　Ｗｉｎｄｏｗｓ　２０００．

Ｐｌｅａｓｅ　ｒｅｆｅｒ　ｔｏ　[Ｗｉｎｄｏｗｓ　２０００＇ｓ　ｓｃｒｅｅｎｓｈｏｔ](http://ecee.colorado.edu/~mathys/ecen1200/hwcl05/explor2000a.png)　ｗｈｅｎ　ｓｔｙｌｉｎｇ．

**Comment by abejfehr** [comment]
Amazing. This is what I had so far, but I'll need to modify the blue gradient in the corner to be based on Windows 2000.

![](http://g.recordit.co/08n1MqjDZY.gif)

Besides that, there's one problem where the dots that connect the folders extend beyond the items in the last folder, as pictured here:

<img width="116" alt="screen shot 2016-06-06 at 23 24 09" src="https://cloud.githubusercontent.com/assets/3917428/15838362/f769c2b2-2c3d-11e6-9118-3087e3dcb474.png">

I don't think there's a way around that with only CSS though, so I think that'll just have to be accepted.

I ❤️ this theme

**Comment by dtinth** [comment]
Ｔｈｉｓ　ｌｏｏｋｓ　ａｗｅｓｏｍｅ！

Ｌｅｔ＇ｓ　ｇｅｔ　ｔｈｉｓ　ｉｎ！　：Ｄ
Ｉ　ｃａｎ　ｈｅｌｐ　ｆｉｘ　ｐｒｏｂｌｅｍ　ａｂｏｕｔ　ｄｏｔｔｅｄ　ｌｉｎｅｓ．

**Comment by abejfehr** [comment]
Just realized having this width at 100% is bad: https://github.com/dtinth/atom-aesthetic-ui/blob/master/styles/tree-view.less#L24

**Comment by dtinth** [comment]
Ｉ　ｑｕｉｃｋ－ｆｉｘｅｄ　ｔｈａｔ　ｂｙ　ａｄｄｉｎｇ：

``` css
pointer-events: none;
```

Ｉ＇ｖｅ　ａｌｓｏ　ｆｉｘｅｄ　ｔｈｅ　ｌａｓｔ　ｉｔｅｍ　ｐｒｏｂｌｅｍ　ｂｙ　ｄｒａｗｉｎｇ　ｄｏｔｓ　ｏｎ　ａｎ　ｉｎｄｉｖｉｄｕａｌ　ｉｔｅｍ　ｒａｔｈｅｒ　ｔｈａｎ　ｏｎ　ｔｈｅ　ｐａｒｅｎｔ．

<img width="200" alt="screen shot 2016-06-08 at 7 36 30" src="https://cloud.githubusercontent.com/assets/193136/15879169/c67eac4e-2d4b-11e6-8fef-bce25b1d4f20.png">

Ｉ　ａｌｓｏ　ｃｈａｎｇｅｄ　ｓｏｍｅ　ｉｃｏｎｓ　ｔｏ　ｂｅ　ｂａｓｅｄ　ｏｎ　Ｗｉｎｄｏｗｓ　２０００．

Ａ　ｎｅｗ　ｖｅｒｓｉｏｎ　ｗｉｌｌ　ｂｅ　ｒｅｌｅａｓｅｄ　ｓｏｏｎ．

**Comment by dtinth** [comment]
Ｒｅｌｅａｓｅｄ　ｖ２．０．０
