### ISSUE TITLE
Syntax doesn't show as in preview pictures?

### ISSUE THREAD

**Issue by devlemire** [dtinth/atom-aesthetic-ui#6]
My syntax is black, and I can't find aesthetic in my syntax drop down menu? What should I do?

**Comment by dtinth** [comment]
ａｅｓｔｈｅｔｉｃ−ｕｉ　ｉｓ　ｊｕｓｔ　ａ　ＵＩ　ｔｈｅｍｅ　ａｎｄ　ｄｏｅｓ　ｎｏｔ　ｃｏｍｅ　ｗｉｔｈ　ａ　ｓｙｎｔａｘ　ｔｈｅｍｅ．

Ｐｌｅａｓｅ　ｉｎｓｔａｌｌ　ａｎｄ　ｕｓｅ　ａｎｙ　ｓｙｎｔａｘ　ｔｈｅｍｅ　ｔｈａｔ　ｙｏｕ　ｌｉｋｅ！

Ｔｈｅ　ｏｎｅ　ｕｓｅｄ　ｉｎ　ｐｒｅｖｉｅｗ　ｐｉｃｔｕｒｅｓ　ｉｓ　[ｒｅｄｍｏｎｄ－ｓｙｎｔａｘ](https://atom.io/themes/redmond-syntax)．
