### ISSUE TITLE
toggleable clippy inspired talking roman bust; an enhancement suggestion

### ISSUE THREAD

**Issue by Bobby-H** [dtinth/atom-aesthetic-ui#7]
love the looks of this theme; didn't think of any improvements until i remembered clippy. could be a toggleable gag as i don't think most users need to be reminded of the right-click. just an idea.

**Comment by dtinth** [comment]
Ｉ　ｒｅｃｏｍｍｅｎｄ　ｉｎｓｔａｌｌｉｎｇ　ａ　ｖｉｒｔｕａｌ　ａｓｓｉｓｔａｎｔ　ｐａｃｋａｇｅ　ｆｏｒ　Ａｔｏｍ，[ｃｌｉｐｐｙ](https://atom.io/packages/clippy)．
